### ISSUE TITLE
Cannot Pull

### ISSUE THREAD

**Issue by Azzammi** [rudi-krsoftware/open-retail#15]
![issueopenretail](https://user-images.githubusercontent.com/23116326/32985864-c974b49c-ccf6-11e7-9c9f-eaf1d276dfa0.png)

Tidak bisa pull project dari github

**Comment by rudi-krsoftware** [comment]
Memang tidak bisa pull om, klo ada perubahan yg blm di commit, atau klo enggak sengaja merubah ya di revert aj.
