### ISSUE TITLE
Bug customer tidak boleh kosong

### ISSUE THREAD

**Issue by cpamungkas** [rudi-krsoftware/open-retail#17]
Saat sedang melakukan transaksi penjualan, terdapat kolom isian customer namun saat klik tombol customer disamping muncul warning "customer - tidak boleh kosong". Dan selalu muncul ketika sudah coba buat data customer baru, sehingga dari sini gagal bertransaksi karna selalu muncul warning tersebut.
versi yang digunakan OpenRetail 1.3.0

![image](https://user-images.githubusercontent.com/1875521/34647906-2a296d68-f3c2-11e7-9b6e-e423699db8db.png)

**Comment by rudi-krsoftware** [comment]
Untuk menonaktifkan validasi *customer tidak boleh kosong* bisa dilakukan melalui menu Pengaturan Umum -> Tab Lainnya.

![screenshot-form-pengaturan-umum-04](https://user-images.githubusercontent.com/24878043/34654728-5a47dfc8-f432-11e7-9181-d14e4a19b622.png)
