### ISSUE TITLE
User boleh pilih data barang atau subjek ketika menginput data transaksi

### ISSUE THREAD

**Issue by helloyud** [rudi-krsoftware/open-retail#18]

**Comment by rudi-krsoftware** [comment]
Saya belum paham om maksudnya, mungkin bisa ditambahkan deskripsi untuk issuenya

**Comment by helloyud** [comment]
coba lihat penjelasannya di sini :
https://images2.imgbox.com/26/5e/Uam18zXR_o.jpg

**Comment by helloyud** [comment]
dari segi fungsional, softwarenya sudah cukup komplit.

tetapi dari segi user interface, belum terlalu mudah untuk dipahami dan perlu diperbaiki supaya user awam dapat mudah memahami meskipun tidak belajar ke buku panduannya.

Terus juga panduan instalasi sebenarnya jangan dibuat terlalu panjang, cukup sesingkatnya saja karena user awam nanti bingung harus memulai dari mana.

Saya juga programmer pak, ini software toko yg saya sudah buat, boleh disimak di:
http://helloyud.blogspot.co.id/2016/12/aplikasi-pertokoan-minimart.html

Kalau bapak tidak keberatan, nanti saya sempatkan utk cek di mana kekurangan dari software bapak (di waktu luang saya), tujuannya semata-mata utk menyempurnakan software bapak. Dari segi fitur saya rasa tidak ada yg perlu diubah, hanya dari segi user interface perlu diperbaiki dan disederhanakan lagi agar user dapat mudah menggunakan softwarenya.

Terima kasih atas perhatiannya.

Salam, Yudhi Pratama Karsa.

**Comment by rudi-krsoftware** [comment]
> coba lihat penjelasannya di sini :
https://images2.imgbox.com/26/5e/Uam18zXR_o.jpg

Udah ada om fasilitas untuk pencarian datanya, om aja yang kurang baca: https://github.com/rudi-krsoftware/open-retail/wiki/Input-Data-Transaksi-Penjualan

**Comment by rudi-krsoftware** [comment]
> tetapi dari segi user interface, belum terlalu mudah untuk dipahami dan perlu diperbaiki supaya user awam dapat mudah memahami meskipun tidak belajar ke buku panduannya.

Pengguna OpenRetail itu udah banyak om, mulai dari [Toko Muslim](http://toko-muslim.com/), [Yufid Store](https://store.yufid.com/), Toko Bangunan, Counter HP, Toko Parfum, Apotik dan masih banyak yg lainnya. Saya belum pernah menerima komplain masalah user interface, yang ada komen mereka "_saya terkesan dengan tampilannya sederhana dan elegan_"

> Terus juga panduan instalasi sebenarnya jangan dibuat terlalu panjang, cukup sesingkatnya saja karena user awam nanti bingung harus memulai dari mana.

Lebih bingungan mana mereka ketika mereka harus menginstall aplikasinya om, mereka harus menginstall manual _Java Runtime Environment_ dan installer MySQL yang masih mentahan dari vendornya. Di installer OpenRetail runtime pendukung seperti .NET Framework  mereka enggak perlu install manual, udah satu paket dengan installernya. Untuk installer databasenya juga tidak saya kasih installer mentahan dari [PostgreSQL](https://www.postgresql.org/), tp sudah saya custome lagi sehingga user hanya perlu menentukan lokasi instalasi, enggak perlu ngeset2x secara manual user database dan mendaftarkan port databasenya ke firewall, semuanya sudah otomatis. Dan seperti yg sudah saya bilang sampai saat ini belum ada yg komplain tentang instalasi OpenRetail

> Saya juga programmer pak, ini software toko yg saya sudah buat, boleh disimak di:
> http://helloyud.blogspot.co.id/2016/12/aplikasi-pertokoan-minimart.html

Manualnya pak, mungkin bisa lebih dikerjaan secara serius, seperti manualnya OpenRetail https://github.com/rudi-krsoftware/open-retail/wiki

> Kalau bapak tidak keberatan, nanti saya sempatkan utk cek di mana kekurangan dari software bapak (di waktu luang saya), tujuannya semata-mata utk menyempurnakan software bapak.

Terima kasih atas saran dan waktunya pak untuk mencoba OpenRetail :-)

**Comment by helloyud** [comment]
Makanya klo ngasih balasan itu jangan Merasa Sombong, kasih masukan yg santun.

Nah ini juga sombong:

"Pengguna OpenRetail itu udah banyak om, mulai dari Toko Muslim, Yufid Store, Toko Bangunan, Counter HP, Toko Parfum, Apotik dan masih banyak yg lainnya. Saya belum pernah menerima komplain masalah user interface, yang ada komen mereka "saya terkesan dengan tampilannya sederhana dan elegan"

Rudi sopan, saya segan.

**Comment by helloyud** [comment]
jelek softwarenya.... hahahaha

**Comment by rudi-krsoftware** [comment]
Ah cape deh

**Comment by helloyud** [comment]
Ah cape deh
