### ISSUE TITLE
file project OpenRetail.T4Generator

### ISSUE THREAD

**Issue by kurniawirawan** [rudi-krsoftware/open-retail#2]
broo ... can't open project OpenRetailT4Generator
![rrr](https://cloud.githubusercontent.com/assets/1389465/21710338/89b5b200-d41a-11e6-8cb4-4b91fd94a9c3.png)

**Comment by coding4ever** [comment]
Memang belum saya tambahkan ke repository, nyusul ya pak boz :-)
