### ISSUE TITLE
Connection String

### ISSUE THREAD

**Issue by afdoal** [rudi-krsoftware/open-retail#23]
mau tanya kang, untuk cnnection string ada di mana??
kalau mau rubah DB make mySQL or SQLite bisa??

**Comment by rudi-krsoftware** [comment]
Untuk ganti database, ada beberapa hal yang perlu dilakukan:

1. Mengganti provider ADO.NET dan string koneksi di class [DapperContext](https://github.com/rudi-krsoftware/open-retail/blob/master/src/OpenRetail.Repository.Service/DapperContext.cs) baris 47 dan 48.
2. Mengganti konfigurasi DbProviderFactories di file [App.Config](https://github.com/rudi-krsoftware/open-retail/blob/master/src/OpenRetail.App/App.config). Ada 3 file App.Config yang harus diganti yaitu di folder [OpenRetail.App](https://github.com/rudi-krsoftware/open-retail/tree/master/src/OpenRetail.App), [OpenRetail.App.Cashier](https://github.com/rudi-krsoftware/open-retail/tree/master/src/OpenRetail.App.Cashier) dan [OpenRetail.WebAPI](https://github.com/rudi-krsoftware/open-retail/tree/master/src/OpenRetail.WebAPI).
3. Penyesuaian query yang mungkin spesifik untuk masing-masing database, misal query LIMIT untuk membatasi record yang ingin ditampilkan.
