### ISSUE TITLE
kasir input penjualan

### ISSUE THREAD

**Issue by dwigkf25** [rudi-krsoftware/open-retail#25]
Siang mas,

maaf sy baru coba belajar install.
terus sy coba input aplikasi kasir untuk penjualan.
1. apakah memang waktu press F4 , list semua CUSTOMER tidak keluar?
2. apakah memang waktu press F3 , list semua KODE BARANG tidak keluar?    
jadi saya mau tidak mau input wild card, misalnya customer GUNTUR, sy ketik GUN saja.

oh ya..spec pc test sy Windows XP SP3.
Terima kasih..sukses slalu

**Comment by rudi-krsoftware** [comment]
1. Ketika menekan shortcut F4, cursor akan fokus di inputan pelanggan, selanjutnya tinggal ketik nama pelanggan, tidak harus lengkap kemudian diakhiri dengan menekan tombol enter. Jika ada nama yg mirip akan tampil popup untuk memilih nama customer.
2. Shortcut F3, itu hanya untuk pindah fokus ke inputkan kode produk, klo mau nyari nama produk, kolom kode produk dikosongkan trus pindah ke kolom nama produk, tinggal cari barang + enter.
