### ISSUE TITLE
Cek Nota Terakhir

### ISSUE THREAD

**Issue by Luqky777** [rudi-krsoftware/open-retail#26]
Siang Mas

Untuk di Cek Nota Terakhir bisa gak mas di kasih penambahan Cetak Nota Terakhir mungkin bisa bermanfaat jika ada kendala koneksi printer kasir terputus. 
Dan satu lagi mas untuk hasil cetak nota kasir info Dibuat oleh Open Retail dts bisa di hilangkan gak mas...

terima kasih..

**Comment by rudi-krsoftware** [comment]
Untuk nomor satu saya list dulu aja requestnya, untuk yg nomor 2 belum bisa om, karena ini aplikasinya gratis jadi ada iklannya.
