### ISSUE TITLE
Download Lambat

### ISSUE THREAD

**Issue by jufryananta** [rudi-krsoftware/open-retail#29]
(maaf) Saya tidak tahu ini harus saya sampaikan dimana. Sepertinya kurang pas juga untuk Pull Req. Jadi disini aja....

Saya lagi cari software kasir. tapi..
Speed Download Github sangat lambat. hanya 1-3kb/s. 13 Jam baru selesai downloadnya.

--> **Mohon diberikan Mirror untuk download**. Makasih.

![Slow Speed](https://user-images.githubusercontent.com/9709267/47256805-bd97af00-d4af-11e8-854b-0ed62c3a7a52.jpg)

![Ping](https://user-images.githubusercontent.com/9709267/47256813-dd2ed780-d4af-11e8-95e7-bb5e4acfa965.jpg)

**Comment by tommyhawk95** [comment]
Selamat malam Pak Jufryananta, Saya barusan mencoba download link tersebut baik2 saja pak. Coba Pak Jufry mencoba mendownload melalui browser lain atau menggunakan internet download m / sebagainya .

**Comment by rudi-krsoftware** [comment]
> Selamat malam Pak Jufryananta, Saya barusan mencoba download link tersebut baik2 saja pak. Silahkan Pak Jufry mencoba mendownload melalui browser lain atau menggunakan internet download m / sebagainya .

Terima kasih om @tommyhawk95, atas informasinya
