### ISSUE TITLE
Control di form di lock?

### ISSUE THREAD

**Issue by Azzammi** [rudi-krsoftware/open-retail#3]
Bagaimana cara mengunlock control tersebut

**Comment by rudi-krsoftware** [comment]
Kelock karena formnya pake template om, jadi klo mau ngedit ya langsung ngedit form templatenya. Form templatenya ada di project [OpenRetail.Helper](https://github.com/rudi-krsoftware/open-retail/tree/master/src/OpenRetail.Helper/UI.Template).

**Comment by Azzammi** [comment]
Ohh oke om. Makasih atas source codenya
