### ISSUE TITLE
request fitur form transaksi penjualan dibuat supaya fullscreen

### ISSUE THREAD

**Issue by troke12** [rudi-krsoftware/open-retail#32]
lebih bagus pada form transaksi penjualan dibuat fullscreen karena pengalaman saya menggunakan beberapa program kasir yg berbayar dibuat seperti itu, supaya tampilan dari windows ga keliatan dan hanya menampilkan Form nya saja dalam bentuk fullscreen

**Comment by tommyhawk95** [comment]
Bro troke12 sudah mencoba Openretail yang "Kasir" belum? Cobain dulu deh 😁

**Comment by troke12** [comment]
saya sudah coba, bagian mana ya untuk fullscreen form only? 
![image](https://user-images.githubusercontent.com/10250068/48606208-001eaf80-e9ba-11e8-8e9b-9ea0e8d0b130.png)

**Comment by troke12** [comment]
maksud saya biar seperti ini form penjualannya, ini yg saya pakai adalah SID Retail
![image](https://user-images.githubusercontent.com/10250068/48606918-71129700-e9bb-11e8-94c0-893657af3b6f.png)
jadi elemen2 dari windows itu ga keliatan

**Comment by rudi-krsoftware** [comment]
Masih kurang cukup kah tampilan seperti ini? Emang ada masalah *penting* apa klo tampilannya enggak fullscreen ?  :-D


![image](https://user-images.githubusercontent.com/10250068/48606208-001eaf80-e9ba-11e8-8e9b-9ea0e8d0b130.png)

**Comment by rudi-krsoftware** [comment]
> Oh yang begitu om, punya versi developernya ga? Kalo punya coba di setting form property nya, rebuild ulang aja. Gitu paling. Atau tunggu pak Komar yang ngerebuild ulang/ update. Atau untuk sementara auto-hidden taskbar dulu hehe.

Saya belum melihat urgensinya untuk menambahkan fitur ini om :-D

**Comment by troke12** [comment]
> > Oh yang begitu om, punya versi developernya ga? Kalo punya coba di setting form property nya, rebuild ulang aja. Gitu paling. Atau tunggu pak Komar yang ngerebuild ulang/ update. Atau untuk sementara auto-hidden taskbar dulu hehe.
> 
> Saya belum melihat urgensinya untuk menambahkan fitur ini om :-D. Pengguna A, nanti membandingkan tampilan dengan software A, pengguna B juga ikut membandingkan dengan tampilan software B, repot donk developnya. Biarlah tampilan seperti ini menjadi ciri khas OpenRetail :-)

maaf mas, maksud saya agar seperti itu supaya keliatan lebih rapi dilihat oleh pembeli, tapi terserah mas juga saya juga gak maksa untuk bikin seperti itu, ini hanya saran dari saya aja supaya keliatan lebih rapi dilihatnya, saya lebih terbiasa seperti itu karena sudah pernah pakai software retail yg lain

**Comment by rudi-krsoftware** [comment]
> > > Oh yang begitu om, punya versi developernya ga? Kalo punya coba di setting form property nya, rebuild ulang aja. Gitu paling. Atau tunggu pak Komar yang ngerebuild ulang/ update. Atau untuk sementara auto-hidden taskbar dulu hehe.
> > 
> > 
> > Saya belum melihat urgensinya untuk menambahkan fitur ini om :-D. Pengguna A, nanti membandingkan tampilan dengan software A, pengguna B juga ikut membandingkan dengan tampilan software B, repot donk developnya. Biarlah tampilan seperti ini menjadi ciri khas OpenRetail :-)
> 
> maaf mas, maksud saya agar seperti itu supaya keliatan lebih rapi dilihat oleh pembeli, tapi terserah mas juga saya juga gak maksa untuk bikin seperti itu, ini hanya saran dari saya aja supaya keliatan lebih rapi dilihatnya, saya lebih terbiasa seperti itu karena sudah pernah pakai software retail yg lain

Oke terima kasih om atas masukannya, utk sementara issue ini saya close dulu ya :-D

**Comment by troke12** [comment]
saya bantu promosi aja, saya masukin OpenRetail kesini https://github.com/GitIndonesia/awesome-indonesia-repo
