### ISSUE TITLE
Coba Koneksi database dari PC lain tidak bisa, PC yg lain Firewall nya harus di Off kan dulu baru bisa

### ISSUE THREAD

**Issue by anggil** [rudi-krsoftware/open-retail#36]
Selamat sore,

pak mau nanya ini saya nyoba koneksi databasenya dari PC lain, jadi 1 PC untuk Kasir dan 1 PC untuk admin server

Pengennya PC kasir pas login ip databasenya mengarahke PC admin server, setelah saya coba login Open RetailCashier dari PC kasir dan di tab connection saya masukkan ip PC admin server.

Ternyata tidak bisa, ada tulisan tidak bisa konek database, silahkan install di drive D bla..blaa.. :smile: 

Tapi ketika saya coba disable Firewall di PC admin server sebagai pusat database, saya bisa login lewat PC kasir

yang saya tanyakan apakah ada cara agar koneksi databse tersebut tidak terblok oleh firewall PC,
soalnya kalau firewall di OFF kan takut kena virus :smiley: 

Oke OM... kami tunggu infonya ... thank

**Comment by rudi-krsoftware** [comment]
Terima kasih om @anggil, atas laporannya.

Perlu diketahui database OpenRetail menggunakan port **5435** untuk menerima koneksi dari pc lain. Jadi om @anggil, tinggal daftarkan saja port **5435** ke [Windows firewall](https://www.dummies.com/computers/operating-systems/windows-7/how-to-open-a-port-in-the-windows-7-firewall/).

**Comment by anggil** [comment]
Siap om rudi, sudah di coba.. dan Work 100% 👍
Terima kasih bantuannya
