### ISSUE TITLE
masalah pada input jumlah barang yang dijual

### ISSUE THREAD

**Issue by monliev** [rudi-krsoftware/open-retail#37]
ketika selesai input barcode, barang akan muncul dan user merubah jumlah barang menjadi 3pcs (minimal grosir 3pcs) maka harga barang akan berubah menjadi harga grosir.

namun ketika barang di scan barcode sejumlah 3x, jumlah barang berubah menjadi 3pcs namun harga barang tidak berubah ke harga grosir, tetap harga normal.

scan > input jumlah barang >  jumlah barang berubah > berubah ke harga grosir (benar)
scan beberapa kali > jumlah barang berubah > harga tetap normal (ini bugnya mungkin).

**Comment by rudi-krsoftware** [comment]
Terima kasih om @monliev atas laporannya bugnya :-)

**Comment by rudi-krsoftware** [comment]
Terima kasih om @monliev, bug ini sudah saya perbaiki
