### ISSUE TITLE
Masalah pada OpenRetailDatabase

### ISSUE THREAD

**Issue by aauwwo** [rudi-krsoftware/open-retail#41]
Sebelumnya OpenRetail berjalan secara normal tidak ada masalah.
Timbul masalah setelah saya tidak sengaja menghapus folder OpenRetailDatabase di drive D: (lokasi instalasi saya).
Ketika saya coba _install_ ulang, muncul pesan:

> Open Retail Database sudah pernah diinstall !!!
> Silakan uninstall terlebih dahulu sebelum melakukan install ulang.
> Kemudian hapus folder 'D:\OpenRetailDatabase'

Dan ketika saya coba saya _uninstall_ melalui Windows Programs dan Features, muncul pesan:

> An error occured while trying to uninstall Open Retail Database. It May have already been uninstalled.

Jadi kedua hal ini saling bertentangan. Di-_install_ tidak bisa di-_uninstall_ juga tidak bisa.

Saya coba meng-_install_ dengan menggunakan database versi development: OpenRetailDatabase-v1.6.3-dev-Setup.exe proses instalasi sukses.

Kemudian saya jalankan lagi program OpenRetail dan OpenRetailCashier namun muncul pesan _error_ setelah _login form_:

> Maaf koneksi ke database gagal !!!
> Disarankan untuk menginstall OpenRetail di 'Drive D'.
> Silahkan uninstall dulu OpenRetailnya, kemudian install lagi di 'Drive D'.

Saya sudah beberapa kali coba _install_ ulang, baik di drive C ataupun D, tapi hasil tetap sama.
Mungkin ada kaitannya dengan masalah yang pertama.

Adakah saran pak @rudi-krsoftware ?
Terima kasih

**Comment by rudi-krsoftware** [comment]
Untuk masalah ini sudah case closed kah om @aauwwo ?

**Comment by aauwwo** [comment]
Untuk masalah _install_ dan _uninstall_ sudah terselesaikan dengan _windows system restore_. Jadi OpenRetailDatabase sudah dapat ter-_install_ kembali.

Namun permasalahan berikutnya tetap sama. Database tetap tidak mau terkoneksi dengan program OpenRetail. Termasuk dengan Tool Backup dan Restore OpenRetail Database, dengan keterangan:

> Maaf koneksi ke database gagal !!!

Apakah ada cara teknis untuk mengatasi hal ini pak @rudi-krsoftware ?

**Comment by rudi-krsoftware** [comment]
Yg diinstal skrg setup OpenRetailDatabase untuk dev ya? Klo iya memang g bisa harus yg untuk production (non dev)

**Comment by aauwwo** [comment]
Bukan. Yang ter-_install_ OpenRetailDatabase biasa, yang versi _development_ sudah saya _uninstall_.

**Comment by rudi-krsoftware** [comment]
Coba masuk ke control panel -> services, kemudian cek status service database open retailnya sudah **Started** atau belum.

![service](https://user-images.githubusercontent.com/24878043/73047628-01dedf80-3ea9-11ea-8145-d4963281ff82.png)

Klo belum jalan ya otomatis aplikasi open retailnya enggak bisa login.

Solusi yang bisa dicoba:

1. Uninstall lagi OpenRetailDatabase kemudian hapus folder instalasinya
1. Restart PC
1. Install lagi OpenRetailDatabase 
1. Cek lagi status servicenya (control panel -> services) klo running harusnya sudah bisa login

**Comment by aauwwo** [comment]
Masalahnya tenyata memang karena _service_ untuk openretail-database yang tidak mau _started_.
Case closed.
Terima kasih pak @rudi-krsoftware
