### ISSUE TITLE
Gagal Back-Up untuk development

### ISSUE THREAD

**Issue by benimaru1** [rudi-krsoftware/open-retail#43]
Maaf bang rudi izin bertanya, kan saya mencoba open retail yang untuk development, nah pas bagian back-up error bang,notifnya seperti gambar dibawah ini. kalo itu errornya dibagian mana ya bang ? padahal codingnya tidak saya otak atik
![Capture](https://user-images.githubusercontent.com/57406677/79008302-4401ee00-7b87-11ea-9b74-048a0b4bf2a1.PNG)

**Comment by rudi-krsoftware** [comment]
Ini langsung jalanin dari source code ya om?

**Comment by benimaru1** [comment]
iya bang, saya coba hasilnya gitu, padahal ga saya otak atik codingnya

**Comment by rudi-krsoftware** [comment]
Coba extrak file **pgsql.zip** ini ke folder bin project **OpenRetail.BackupAndRestore**

[pgsql.zip](https://github.com/rudi-krsoftware/open-retail/files/4536912/pgsql.zip)

**Comment by benimaru1** [comment]
siap terima kasih mas,sudah bisa
