### ISSUE TITLE
Tidak bisa bertransaksi jika salah satu produk stoknya habis di etalase atau gudang?

### ISSUE THREAD

**Issue by siigitmardiansyaah** [rudi-krsoftware/open-retail#44]
maaf bang rudi saya ingin bertanya bang,
apakah bisa semisal stok di etalase dan gudang itu jika sudah dibawah minimal stok di gudang itu tidak bisa bertransaksi ? soalnya tadi saya coba ketika stok di etalase dan gudang sudah habis masih bisa untuk bertransaksi di produk tersebut dan notif untuk minimal stoknya muncul di admin

**Comment by rudi-krsoftware** [comment]
Bisa om, tinggal nonaktifkan settinganya di menu pangaturan umum

![pengaturan umum](https://user-images.githubusercontent.com/24878043/80566855-15f12a80-8a1e-11ea-8ed7-03abb27aca31.png)

**Comment by siigitmardiansyaah** [comment]
maaf bang rudi mau nanya,
![gambar](https://user-images.githubusercontent.com/57787826/80838421-30e0bc00-8c23-11ea-9c9e-f8caac70611e.png)
pas saya mau back up database muncul error seperti ini bang, saya salah dimana ya ?

**Comment by rudi-krsoftware** [comment]
Issues sebelumnya gimana om? Klo udah selesai di close dulu aja, trus utk pertanyaan backup dan restorenya di buat issue baru

**Comment by siigitmardiansyaah** [comment]
oiya siap mohon maaf bang rudi
