### ISSUE TITLE
Muncul Error port pada saat backup database

### ISSUE THREAD

**Issue by siigitmardiansyaah** [rudi-krsoftware/open-retail#45]
![Capture](https://user-images.githubusercontent.com/57787826/80864055-40efae80-8caa-11ea-98a8-42e8af678c2e.PNG)
maaf bang rudi mau nanya lagi, muncul error port pas saya lagi mau backup database bang

**Comment by rudi-krsoftware** [comment]
Ini jalanin toolnya dari source code atau hasil installan?

**Comment by siigitmardiansyaah** [comment]
dari source code mas

**Comment by rudi-krsoftware** [comment]
Sudah nyobain solusi di issue #43 belum om?
